[tool.poetry]
name = "app"
version = "0.1.0"
description = "FUTSALA"
authors = ["Sujalcha7 <sujalkoju97@gmail.comâ€>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.30.6"
fastapi = "^0.112.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
